apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rolling
spec:
  replicas: 10
  minReadySeconds: 10
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 5
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: my-container
          image: hkshitesh/kubedemo:2.0
          ports:
            - containerPort: 80
