apiVersion: v1
kind: Pod
metadata:
  name: my-labeled-pod
  labels:
    app: webserver
    environment: production
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
