apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset1
spec:
  replicas: 2
  selector:
    matchLabels:
      app1: my-app1
      app2: my-app2
  template:
    metadata:
      labels:
        app1: my-app1
        app2: my-app2
    spec:
      containers:
        - name: nginx
          image: httpd:latest
          ports:
            - containerPort: 80
