apiVersion: v1
data:
  password: J1BAc3N3MHJkJw==
  username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2025-08-07T21:57:57Z"
  name: my-secret
  namespace: default
  resourceVersion: "540953"
  uid: 4ca65251-30aa-4a76-acb7-8d617a42f9de
type: Opaque
