apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: my-namespace
spec:
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
